### ISSUE TITLE
Dependency algorithm not found.

### ISSUE THREAD

**Issue by us** [fetlang/fetlang#13]
⋊> ~/g/fetlang on master ◦ meson --buildtype=release src build                                                                                                                           23:06:09
The Meson build system
Version: 0.44.0.dev1
Source dir: /Users/syny/github/fetlang/src
Build dir: /Users/syny/github/fetlang/build
Build type: native build
Project name: Fetlang
Native C compiler: cc (clang 9.0.0)
Native C++ compiler: c++ (clang 9.0.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64

Meson encountered an error in file meson.build, line 12, column 0:
Dependency algorithm not found. It is not a valid boost library.

A full log can be found at /Users/syny/github/fetlang/build/meson-logs/meson-log.txt

**Comment by Property404** [comment]
Hi! - I turned off using the system's boost by default - please see if that fixes the issue
